# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Travels' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Travels

  target 'Travels-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TravelsTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Travels-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Travels-tvOS

  target 'Travels-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
